// AUTOGENERATED FILE
// This file was generated from numbers.ohm by `ohm generateBundles`.

import {
  BaseActionDict,
  Grammar,
  IterationNode,
  Node,
  NonterminalNode,
  Semantics,
  TerminalNode
} from 'ohm-js';

export interface numbersActionDict<T> extends BaseActionDict<T> {
  Exp?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  UnaryExp_pos?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  UnaryExp_neg?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  UnaryExp?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  exponentPart?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: IterationNode) => T;
  number_leftside?: (this: NonterminalNode, arg0: IterationNode, arg1: IterationNode, arg2: IterationNode, arg3: IterationNode) => T;
  number_rightside?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: IterationNode) => T;
  number?: (this: NonterminalNode, arg0: NonterminalNode) => T;
}

export interface numbersSemantics extends Semantics {
  addOperation<T>(name: string, actionDict: numbersActionDict<T>): this;
  extendOperation<T>(name: string, actionDict: numbersActionDict<T>): this;
  addAttribute<T>(name: string, actionDict: numbersActionDict<T>): this;
  extendAttribute<T>(name: string, actionDict: numbersActionDict<T>): this;
}

export interface numbersGrammar extends Grammar {
  createSemantics(): numbersSemantics;
  extendSemantics(superSemantics: numbersSemantics): numbersSemantics;
}

declare const grammar: numbersGrammar;
export default grammar;

